export const GET_WATCHES = 'GET_WATCHES'
export const SORT_WATCHES = 'SORT_WATCHES'
export const ADD_WATCH = 'ADD_WATCH'
export const EDIT_WATCH = 'EDIT_WATCH'
export const DELETE_WATCH = 'DELETE_WATCH'
export const CLEAR_WATCHES = 'CLEAR_WATCHES'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'
export const WATCH_MAKER_SORT = 'Watch_Maker_sort'
export const WATCH_NAME_SORT = 'Watch_Name_sort'
export const NEWEST_TO_OLDEST_SORT = 'Newest_to_Oldest_sort'
export const OLDEST_TO_NEWEST_SORT = 'Oldest_to_Newest_sort'
export const COST_LOW_TO_HIGH_SORT = 'Cost_Low_to_High_sort'
export const COST_HIGH_TO_LOW_SORT = 'Cost_High_to_Low_sort'
              